// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: persona/api/user.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_type "github.com/johnbellone/persona-service/proto/persona/type"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	status "google.golang.org/genproto/googleapis/rpc/status"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for UserService service

func NewUserServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{
		&api.Endpoint{
			Name:    "UserService.Create",
			Path:    []string{"/api/v1/users"},
			Method:  []string{"POST"},
			Body:    "",
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "UserService.Get",
			Path:    []string{"/api/v1/users/{param}"},
			Method:  []string{"GET"},
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "UserService.Update",
			Path:    []string{"/api/v1/users/{param}"},
			Method:  []string{"PUT"},
			Body:    "",
			Handler: "rpc",
		},
		&api.Endpoint{
			Name:    "UserService.Delete",
			Path:    []string{"/api/v1/users/{param}"},
			Method:  []string{"DELETE"},
			Body:    "",
			Handler: "rpc",
		},
	}
}

// Client API for UserService service

type UserService interface {
	Create(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error)
	Get(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*_type.User, error)
	Update(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error)
	Delete(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) Create(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error) {
	req := c.c.NewRequest(c.name, "UserService.Create", in)
	out := new(status.Status)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Get(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*_type.User, error) {
	req := c.c.NewRequest(c.name, "UserService.Get", in)
	out := new(_type.User)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Update(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error) {
	req := c.c.NewRequest(c.name, "UserService.Update", in)
	out := new(status.Status)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Delete(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*status.Status, error) {
	req := c.c.NewRequest(c.name, "UserService.Delete", in)
	out := new(status.Status)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	Create(context.Context, *UserRequest, *status.Status) error
	Get(context.Context, *UserRequest, *_type.User) error
	Update(context.Context, *UserRequest, *status.Status) error
	Delete(context.Context, *UserRequest, *status.Status) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) error {
	type userService interface {
		Create(ctx context.Context, in *UserRequest, out *status.Status) error
		Get(ctx context.Context, in *UserRequest, out *_type.User) error
		Update(ctx context.Context, in *UserRequest, out *status.Status) error
		Delete(ctx context.Context, in *UserRequest, out *status.Status) error
	}
	type UserService struct {
		userService
	}
	h := &userServiceHandler{hdlr}
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.Create",
		Path:    []string{"/api/v1/users"},
		Method:  []string{"POST"},
		Body:    "",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.Get",
		Path:    []string{"/api/v1/users/{param}"},
		Method:  []string{"GET"},
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.Update",
		Path:    []string{"/api/v1/users/{param}"},
		Method:  []string{"PUT"},
		Body:    "",
		Handler: "rpc",
	}))
	opts = append(opts, api.WithEndpoint(&api.Endpoint{
		Name:    "UserService.Delete",
		Path:    []string{"/api/v1/users/{param}"},
		Method:  []string{"DELETE"},
		Body:    "",
		Handler: "rpc",
	}))
	return s.Handle(s.NewHandler(&UserService{h}, opts...))
}

type userServiceHandler struct {
	UserServiceHandler
}

func (h *userServiceHandler) Create(ctx context.Context, in *UserRequest, out *status.Status) error {
	return h.UserServiceHandler.Create(ctx, in, out)
}

func (h *userServiceHandler) Get(ctx context.Context, in *UserRequest, out *_type.User) error {
	return h.UserServiceHandler.Get(ctx, in, out)
}

func (h *userServiceHandler) Update(ctx context.Context, in *UserRequest, out *status.Status) error {
	return h.UserServiceHandler.Update(ctx, in, out)
}

func (h *userServiceHandler) Delete(ctx context.Context, in *UserRequest, out *status.Status) error {
	return h.UserServiceHandler.Delete(ctx, in, out)
}
